import 'package:toplansin_cleanarch/domain/entities/venue_entity.dart';

/// Halı saha mock verileri - geliştirme / UI testi için.
///
/// Kullanım:
/// 1) Liste: `final venues = MockVenues.list;`
/// 2) Bloc state boşken UI'da göstermek: BlocBuilder içinde
///    `final items = state.premiumVenues.whereType<VenueEntity>().toList();
///     final displayList = items.isEmpty ? MockVenues.list : items;`
/// 3) ListView: `ListView.builder(itemCount: MockVenues.list.length,
///    itemBuilder: (_, i) => VenueCard(venue: MockVenues.list[i], ...))`
abstract class MockVenues {
  static const String _ownerId = 'owner_1';

  static List<VenueEntity> get list => [
        VenueEntity(
          id: 'v1',
          ownerId: _ownerId,
          name: 'Uçar Spor Tesisleri',
          location: 'Üsküdar, İstanbul',
          price: 4500,
          rating: 8.4,
          imagesUrl: ['https://firebasestorage.googleapis.com/v0/b/toplansin-e4363.firebasestorage.app/o/halisaha0.jpg?alt=media&token=f3404d41-dd68-4653-911c-e6fa759ce409'],
          bookedSlots: [],
          startHour: '09:00',
          endHour: '23:00',
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          isPremium: true,
          viewCount: 1250,
          totalReviews: 77,
          hasParking: true,
          hasShowers: true,
          hasShoeRental: true,
          hasCafeteria: true,
          hasNightLighting: true,
          hasMaleToilet: true,
          hasFemaleToilet: true,
          hasFoodService: true,
          acceptsCreditCard: true,
          hasFoosball: false,
          hasCameras: true,
          hasGoalkeeper: false,
          hasPlayground: false,
          hasPrayerRoom: true,
          hasInternet: true,
          description: 'Merkezi konumda, yapay çim saha.',
          size: '40x20',
          surface: 'Yapay çim',
          maxPlayers: 14,
          phone: '+90 212 XXX XX XX',
          latitude: 41.0082,
          longitude: 29.0154,
        ),
        VenueEntity(
          id: 'v2',
          ownerId: _ownerId,
          name: 'Kadıköy Halı Saha',
          location: 'Kadıköy, İstanbul',
          price: 3800,
          rating: 7.8,
          imagesUrl: ['https://picsum.photos/400/261'],
          bookedSlots: [],
          startHour: '08:00',
          endHour: '24:00',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          isPremium: false,
          viewCount: 890,
          totalReviews: 42,
          hasParking: true,
          hasShowers: true,
          hasShoeRental: false,
          hasCafeteria: false,
          hasNightLighting: true,
          hasMaleToilet: true,
          hasFemaleToilet: true,
          hasFoodService: false,
          acceptsCreditCard: true,
          hasFoosball: true,
          hasCameras: false,
          hasGoalkeeper: false,
          hasPlayground: false,
          hasPrayerRoom: false,
          hasInternet: true,
          description: 'Kadıköy merkezde kapalı saha.',
          size: '38x18',
          surface: 'Halı',
          maxPlayers: 12,
          phone: '+90 216 XXX XX XX',
          latitude: 40.9927,
          longitude: 29.0234,
        ),
        VenueEntity(
          id: 'v3',
          ownerId: _ownerId,
          name: 'Beşiktaş Arena',
          location: 'Beşiktaş, İstanbul',
          price: 5200,
          rating: 9.0,
          imagesUrl: ['https://picsum.photos/400/262'],
          bookedSlots: [],
          startHour: '07:00',
          endHour: '23:00',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          isPremium: true,
          viewCount: 2100,
          totalReviews: 156,
          hasParking: true,
          hasShowers: true,
          hasShoeRental: true,
          hasCafeteria: true,
          hasNightLighting: true,
          hasMaleToilet: true,
          hasFemaleToilet: true,
          hasFoodService: true,
          acceptsCreditCard: true,
          hasFoosball: true,
          hasCameras: true,
          hasGoalkeeper: false,
          hasPlayground: false,
          hasPrayerRoom: true,
          hasInternet: true,
          description: 'Profesyonel standartlarda yapay çim.',
          size: '42x22',
          surface: 'Yapay çim',
          maxPlayers: 14,
          phone: '+90 212 XXX XX XX',
          latitude: 41.0422,
          longitude: 29.0066,
        ),
        VenueEntity(
          id: 'v4',
          ownerId: _ownerId,
          name: 'Şirinevler Spor Kompleksi',
          location: 'Şirinevler, İstanbul',
          price: 3200,
          rating: 7.5,
          imagesUrl: ['https://picsum.photos/400/263'],
          bookedSlots: [],
          startHour: '09:00',
          endHour: '22:00',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          isPremium: false,
          viewCount: 540,
          totalReviews: 28,
          hasParking: true,
          hasShowers: true,
          hasShoeRental: false,
          hasCafeteria: true,
          hasNightLighting: true,
          hasMaleToilet: true,
          hasFemaleToilet: true,
          hasFoodService: true,
          acceptsCreditCard: true,
          hasFoosball: false,
          hasCameras: false,
          hasGoalkeeper: false,
          hasPlayground: false,
          hasPrayerRoom: true,
          hasInternet: true,
          description: 'Şirinevler metro yakınında halı saha.',
          size: '40x20',
          surface: 'Halı',
          maxPlayers: 14,
          phone: '+90 212 XXX XX XX',
          latitude: 41.0789,
          longitude: 28.9876,
        ),
        VenueEntity(
          id: 'v5',
          ownerId: _ownerId,
          name: 'Ataşehir Futbol Merkezi',
          location: 'Ataşehir, İstanbul',
          price: 4800,
          rating: 8.6,
          imagesUrl: ['https://picsum.photos/400/264'],
          bookedSlots: [],
          startHour: '08:00',
          endHour: '24:00',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          isPremium: true,
          viewCount: 1680,
          totalReviews: 92,
          hasParking: true,
          hasShowers: true,
          hasShoeRental: true,
          hasCafeteria: true,
          hasNightLighting: true,
          hasMaleToilet: true,
          hasFemaleToilet: true,
          hasFoodService: true,
          acceptsCreditCard: true,
          hasFoosball: true,
          hasCameras: true,
          hasGoalkeeper: false,
          hasPlayground: false,
          hasPrayerRoom: true,
          hasInternet: true,
          description: 'Ataşehir merkezde yapay çim saha.',
          size: '42x22',
          surface: 'Yapay çim',
          maxPlayers: 14,
          phone: '+90 216 XXX XX XX',
          latitude: 40.9923,
          longitude: 29.1244,
        ),
        VenueEntity(
          id: 'v6',
          ownerId: _ownerId,
          name: 'Bakırköy Sahil Saha',
          location: 'Bakırköy, İstanbul',
          price: 4100,
          rating: 8.0,
          imagesUrl: ['https://picsum.photos/400/265'],
          bookedSlots: [],
          startHour: '07:00',
          endHour: '23:00',
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
          isPremium: false,
          viewCount: 720,
          totalReviews: 35,
          hasParking: true,
          hasShowers: true,
          hasShoeRental: true,
          hasCafeteria: false,
          hasNightLighting: true,
          hasMaleToilet: true,
          hasFemaleToilet: true,
          hasFoodService: false,
          acceptsCreditCard: true,
          hasFoosball: false,
          hasCameras: false,
          hasGoalkeeper: false,
          hasPlayground: false,
          hasPrayerRoom: false,
          hasInternet: true,
          description: 'Bakırköy sahil yolunda açık hava sahası.',
          size: '38x18',
          surface: 'Yapay çim',
          maxPlayers: 12,
          phone: '+90 212 XXX XX XX',
          latitude: 40.9762,
          longitude: 28.8772,
        ),
      ];
}
